common/models/CatalogSubcat.php
<?php
namespace common\models;

use Yii;
use yii\base\Exception;
use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
use common\models\CatalogPosition;
use common\components\Table;

/**
 * CatalogSubcat model
 *
 * @property integer $id
 * @property string $date_create
 * @property string $date_update
 * @property string $who_create
 * @property string $who_update
 * @property string $title
 * @property string $author
 * @property string $year
 * @property string $metatitle
 * @property string $description
 * @property string $keywords
 * @property string $content
 * @property string $foto
 * @property string $foto_small
 * @property integer $sort
 *
 */
class CatalogSubcat extends ActiveRecord
{
    const STATUS_INACTIVE = 1;
    const STATUS_ACTIVE = 0;
    
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'date_create',
                'updatedAtAttribute' => 'date_update',
                'value' => new Expression('NOW()'),
            ],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return Table::get('catalog_subcat');
    }
    
    public function formName()
    {
        return '';
    }
    
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'date_create' => 'Дата создания',
            'date_update' => 'Дата обновления',
            'title' => 'Наименование',
            'author' => 'Автор',
            'year' => 'Год',
            'metatitle' => 'Заголовок страницы, тег <title>',
            'description' => 'Мета-тег Description',
            'keywords' => 'Мета-тег Keywords',
            'content' => 'Содержание страницы',
            'sort' => 'Приоритет',
            'foto' => 'Фотография',
            'foto_small' => 'Миниатюра фотографии',
        ];
    }
    
    public function rules()
    {
        return [
            [
                [
                    'title',
                    'author',
                    'year',
                    'metatitle',
                    'description',
                    'keywords',
                    'content',
                ],
                'string',
            ],
            [
                [
                    'title',
                ],
                'required',
            ],
            [
                'sort',
                'integer',
            ],

        ];
    }

    public function getPosition()
    {
        return $this->hasMany(CatalogPosition::className(), ['subcat' => 'id']);
    }    

    public function getCat() {
        return $this->hasOne(CatalogSubcatCat::className(), ['id_subcat' => 'id']);
    }

    public function getId()
    {
        return $this->id;
    }

    public function beforeValidate()
    {
        try {
            //
        } catch (Exception $e) {
            //
        }
        return true;
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            try {
            } catch (Exception $e) {
                //
            }
            return true;
        } else {
            return false;
        }
    }
}

backend/controllers/CatalogSubcatController.php
<?php
namespace backend\controllers;

use common\models\CatalogSubcatCat;
use Yii;
use yii\base\Exception;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;
use backend\components\IP;
use backend\components\Notice;
use common\models\Admin;
use common\models\CatalogSubcat;
use backend\models\CatalogSubcatUpload;
use backend\models\CatalogSubcatSearch;

/**
 * CatalogSubcat controller
 */
class CatalogSubcatController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //                'user' => 'common\models\Users',
                'rules' => [
                    [
                        'actions' => [
                            'login',
                            'error',
                        ],
                        // Define specific actions
                        'allow' => true,
                        // Has access
                        'roles' => ['@'],
                        // '@' All logged in users / or your access role e.g. 'admin', 'user'
                    ],
                    [
                        'allow' => false,
                        // Do not have access
                        'roles' => ['?'],
                        // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public $params = [];
    /**
     * @inheritdoc
     */
    public $layout = '@app/views/layouts/main.php';

    public function actions()
    {
        return [
            'errorHandler' => [
                'errorAction' => 'site/login',
            ],
        ];
    }

    public function beforeAction($action)
    {
        return (Admin::checkAuth($this) && self::checkRights());
    }

    public function checkRights()
    {
        if (!Yii::$app->authManager->checkAccess(Yii::$app->view->params['id_role'], 'managementCatalog')) {
            $this->redirect('/site/norights/')->send();
            return false;
        }
        return true;
    }

    public function actionShow()
    {
        $searchModel = new CatalogSubcatSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $data = [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ];
        return $this->render('show', $data);
    }

    /* @param integer $id
     * @return mixed
     */
    public function actionForm($id = 0)
    {
        $model = $id == 0 ? new CatalogSubcat() : $this->findModel($id);
        $modelCat = $id == 0 ? new CatalogSubcatCat() : $this->findModelCat($id);
        return $this->render('form', [
            'model' => $model,
            'modelCat' => $modelCat,
        ]);
    }

    public function actionCreate()
    {
        $model = new CatalogSubcat();
        $model->who_create = IP::whoCreate();
        $model->who_update = IP::whoCreate();
        $post = Yii::$app->request->post();
        $errorFilesArray = [
            'foto' => [],
            'foto_small' => [],
        ];

        if ($model->load($post) && $model->save()) {
            $id = $model->getPrimaryKey();
            $model->sort = $id;
            $model->update();

            $modelCat = $this->findModelCat($id) !== null ? $this->findModelCat($id) : new CatalogSubcatCat();
            $modelCat->id_subcat = $id;
            if ($modelCat->load($post) && $modelCat->save()) {

            }

            $filePath = CatalogSubcatUpload::filePath();
            $modelUpload = new CatalogSubcatUpload();
            $modelUpload->load($post);
            $foto = UploadedFile::getInstance($modelUpload, 'foto');
            $modelUpload->foto = $foto;
            
            if (($foto && $foto->tempName) && ($modelUpload->validate())) {
                $nameFile = implode('', [
                    md5(microtime(true)),
                    '.',
                    $foto->extension,
                ]);
                $nameSmallFile = implode('', [
                    md5($nameFile),
                    '.',
                    $foto->extension,
                ]);
                
                if ($foto->saveAs($filePath . $nameFile)) {
                    $model->foto = $nameFile;
                    CatalogSubcatUpload::changeSize($model->foto, 'foto');
                    chmod($filePath . $model->foto, 0644);
                    $model->foto_small = $nameSmallFile;
                    copy($filePath . $model->foto, $filePath . $model->foto_small);
                    CatalogSubcatUpload::changeSize($model->foto_small, 'foto_small');
                    chmod($filePath . $model->foto_small, 0644);
                }
            } elseif (!empty($modelUpload->errors['foto'])) {
                $errorFilesArray['foto'] = array_merge($errorFilesArray['foto'], $modelUpload->errors['foto']);
            }
            $model->update();

            $url = array_merge([
                'form',
                'id' => $id,
                'edit' => 'ok',
            ], array_filter([
                'cat' => Yii::$app->request->get('cat'),
            ]));

            $errorText = '';
            foreach ($errorFilesArray as $key => $array) {
                if (!empty($array)) {
                    $errorText .= ' ' . implode(' ', $array);
                }
            }
            if (empty($errorText)) {
                Notice::send($message = 'Методичка успешно создана', $id_type = Notice::info, $id = Url::to($url));
            } else {
                Notice::send($message = 'Методичка создана с некоторыми ошибками.' . $errorText, $id_type =
                    Notice::warning, $id = Url::to($url));
            }

            echo "<script>document.location='" . Url::to($url) . "';</script>";
            return true;
        } else {
        }
        return false;
    }
    
    public function actionValidate()
    {
        $arrayError = [];
        
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost) {
            $model = new CatalogSubcat();
            $modelCat = new CatalogSubcatCat();
            $post = Yii::$app->request->post();
            if ($model->load($post)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $arrayError = array_merge($arrayError, ActiveForm::validate($model));
                return $arrayError;
            } else {
            }
            if ($modelCat->load($post)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $arrayError = array_merge($arrayError, ActiveForm::validate($modelCat));
                return $arrayError;
            } else {
            }
        }
        return false;
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->who_update = IP::whoCreate();
        $post = Yii::$app->request->post();
        $errorFilesArray = [
            'foto' => [],
            'foto_small' => [],
        ];

        if ($model->load($post) && $model->save()) {
            $id = $model->getPrimaryKey();
        
            $modelCat = $this->findModelCat($id) !== null ? $this->findModelCat($id) : new CatalogSubcatCat();
            $modelCat->id_subcat = $id;
            if ($modelCat->load($post) && $modelCat->save()) {

            }

            $filePath = CatalogSubcatUpload::filePath();
            $modelUpload = new CatalogSubcatUpload();
            $modelUpload->load($post);
            $foto = UploadedFile::getInstance($modelUpload, 'foto');
            $modelUpload->foto = $foto;

            if ($modelUpload->delete_foto) {
                if (is_file($filePath . $model->foto)) {
                    unlink($filePath . $model->foto);
                }
                if (is_file($filePath . $model->foto_small)) {
                    unlink($filePath . $model->foto_small);
                }
                $model->foto = '';
                $model->foto_small = '';
                $model->update();
            }

            if (($foto && $foto->tempName) && ($modelUpload->validate())) {
                $nameFile = implode('', [
                    md5(microtime(true)),
                    '.',
                    $foto->extension,
                ]);
                $nameSmallFile = implode('', [
                    md5($nameFile),
                    '.',
                    $foto->extension,
                ]);
                if ($foto->saveAs($filePath . $nameFile)) {
                    $model->foto = $nameFile;
                    CatalogSubcatUpload::changeSize($model->foto, 'foto');
                    chmod($filePath . $model->foto, 0644);
                    $model->foto_small = $nameSmallFile;
                    copy($filePath . $model->foto, $filePath . $model->foto_small);
                    CatalogSubcatUpload::changeSize($model->foto_small, 'foto_small');
                    chmod($filePath . $model->foto_small, 0644);
                    $model->update();
                }
            } elseif (!empty($modelUpload->errors['foto'])) {
                $errorFilesArray['foto'] = array_merge($errorFilesArray['foto'], $modelUpload->errors['foto']);
            }

            $url = [
                'form',
                'id' => $id,
                'edit' => 'ok',
            ];

            $errorText = '';
            foreach ($errorFilesArray as $key => $array) {
                if (!empty($array)) {
                    $errorText .= ' ' . implode(' ', $array);
                }
            }

backend/views/catalog-subcat/_form.php
<?php

/**
 *
 * @var $this yii\web\View
 * @var $result
 * @var $submit
 * @var $duplicate
 * @var $model common\models\CatalogSubcat
 * @var $modelSubcatCat common\models\CatalogSubcatCat
 *
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\validators\FileValidator;
use yii\widgets\ActiveForm;
use yii\web\View;
use backend\assets\Select2Asset;
use backend\assets\CkeditorAsset;
use backend\models\CatalogSubcatUpload;
use backend\components\Common;
use backend\components\Notice;
use common\models\CatalogCat;
use common\models\University;
use kartik\select2\Select2;
use common\models\UserCatalog;

$bundle_ckeditor = CkeditorAsset::register(Yii::$app->view);
Select2Asset::register(Yii::$app->view);
$this->registerJsFile('/lib/ajexfilemanager/ajex.js', ['position' => View::POS_END]);

$fileUrl = CatalogSubcatUpload::fileUrl();
$filePath = CatalogSubcatUpload::filePath();

$db = Yii::$app->db;
extract($result, EXTR_OVERWRITE);
/**
 * @var $submit string
 * @var $id integer
 */

$form_arr = [
    'options' => ['class' => 'form-group'],
    'errorOptions' => ['class' => 'form_error'],
    'labelOptions' => ['class' => 'form_title'],
    'inputOptions' => ['class' => 'form_input'],
];
$radio_arr = [
    'errorOptions' => ['class' => 'form_error'],
    'labelOptions' => ['class' => 'form_title'],
    'inputOptions' => ['class' => 'form_radio'],
];

$filterCat = [];
$filterCat[] = 'and';
if (Yii::$app->view->params['id_role'] == 1) {
    $filterCat[] = [
        'in',
        'id',
        UserCatalog::find()->select(['id_cat'])->where(['id_user' => Yii::$app->view->params['id_user']]),
    ];
}

$categories = CatalogCat::find()->where($filterCat)->orderBy(['title' => SORT_ASC])->asArray()->all();
$categories = ArrayHelper::map($categories, 'id', 'title');
$universities = University::find()->orderBy(['title' => SORT_ASC])->asArray()->all();
$universities = ArrayHelper::map($universities, 'id', 'title');
$modelUpload = new CatalogSubcatUpload();
?>
    <div class="post-form">
        <?php $form = ActiveForm::begin([
            'id' => 'dynamic-form',
            'action' => [
                $url_action,
                'id' => $model->id,
            ],
            'fieldConfig' => $form_arr,
            //         'enableClientValidation' => true,
            'enableClientValidation' => false,
            'enableAjaxValidation' => true,
            'validationUrl' => $url_validate,
            'options' => [
                'enctype' => 'multipart/form-data',
            ],
        ]); ?>
        <article>
            <div class='section_stripe'></div>
            <div class='section_info'>
                <?php Notice::init(); ?>
    
                <?= $form->field($model, 'title')->textInput(); ?>
    
                <?= $form->field($modelSubcatCat, 'id_cat')->widget(Select2::className(), [
                    'data' => $categories,
                    'language' => 'ru',
                    'options' => [
                        'placeholder' => 'Выберите дисциплину',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ])->label($modelSubcatCat->attributeLabels()['id_cat'], ['class' => 'form_title form_select']); ?>
    
                <?= $form->field($modelSubcatCat, 'id_university')->widget(Select2::className(), [
                    'data' => $universities,
                    'language' => 'ru',
                    'options' => [
                        'placeholder' => 'Выберите университет',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                    ],
                ])->label($modelSubcatCat->attributeLabels()['id_university'], ['class' => 'form_title form_select']); ?>
    
                <?= $form->field($model, 'year')->textInput(); ?>
                <?= $form->field($model, 'author')->textInput(); ?>
                <?= $form->field($model, 'metatitle')->textInput(); ?>
                <?= $form->field($model, 'description')->textarea([
                    'rows' => '4',
                ]); ?>
                <?= $form->field($model, 'keywords')->textarea([
                    'rows' => '4',
                ]); ?>
                <div class="section_title"><?= $model->attributeLabels()['content'] ?></div>
                <div class="section_input">
                <?= $form->field($model, 'content', [
                    'options' => [
                        'class' => 'form-group form-wysiwyg',
                    ],
                ])->textarea([])->label(false); ?>
                </div>
                <script>
                    $(function () {
                        var ckeditor = CKEDITOR.replace('content', {
                            customConfig: '/lib/ckeditor/config.js'
                        });
                        AjexFileManager.init({returnTo: 'ckeditor', editor: ckeditor});
                    });
                </script>
                
                <div class='section_title' style="margin-top: 0;">
                    Прикрепляемый файл (в формате jpg, png или gif,
                    размер не более
                    <?= str_replace('и', '', Yii::$app->formatter->asShortSize((new FileValidator)->getSizeLimit())) ?>)
                </div>
                <?php
                if (is_file($filePath . $model->foto) && is_file($filePath . $model->foto_small)) {
                    ?>
                    <div class="section_doc">
                        <div class="icon">
                            <? echo Html::a(Html::img($fileUrl .
                                $model->foto_small, ['width' => 100]), Url::to($fileUrl . $model->foto), [
                                'data' => ['fancybox' => 'gallery'],
                                'target' => '_blank',
                            ]); ?>
                        </div>
                        <div class="title" title="<?= $model->foto ?>">
                            <?
                            echo implode('', [
                                Common::formatLongName($model->foto),
                                '<br><span>',
                                Common::formatFileSize(filesize($filePath . $model->foto)),
                                '</span>',
                            ]);
                            ?>
                        </div>
                        <div class="delete">
                            <? echo $form->field($modelUpload, 'delete_foto', [
                                'options' => ['class' => 'form-group form-checkbox',],
                            ])->checkbox(['class' => 'span-1']); ?>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <div class="section_checkbox">
                    <? echo $form->field($modelUpload, 'foto', [
                        'options' => ['class' => 'form-group form-file',],
                    ])->fileInput(['accept' => '.jpg, .png, .gif'])->label(false); ?>
                </div>

            </div>

            <div class='section_stripe2'></div>
            <?php
            echo Html::submitButton($submit, [
                'id' => 'submiting',
                'class' => 'btn btn-primary section_submit',
            ]);
            ?>
        </article>
        <?php ActiveForm::end(); ?>
    </div>
<?
$this->registerJsFile('/js/catalog_subcat_add.js', ['position' => yii\web\View::POS_END]);

backend/views/catalog-subcat/_search.php
<?php
/**
 * @var $this yii\web\View
 * @var $model backend\models\CatalogSubcatSearch
 * @var $form yii\widgets\ActiveForm
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use common\models\University;

$id_type = $model->getId_type();
$search_word = $model->getSearch_word();
$filter_arr = [
    1 => 'Частичное совпадение с любым из слов',
    2 => 'Частичное совпадение с каждым из слов',
    3 => 'Точное совпадение',
];
$filter2_arr = [
    1 => 'Любое из слов',
    2 => 'Все слова',
    3 => 'Как в запросе',
];

$universities = University::find()->orderBy(['sort' => SORT_ASC, 'title' => SORT_ASC])->asArray()->all();
$universities = ArrayHelper::map($universities, 'id', 'title');

?>
<div class="post-search">
    <?php Pjax::begin(['id' => 'search']) ?>
    <?php $form = ActiveForm::begin([
        'action' => ['show'],
        'method' => 'get',
        'options' => ['data-pjax' => true, 'id' => 'search_form'],
    ]); ?>
    <div class="filter">
        <div class="row">
            <div class="col-xs-4">
                <div class="input-group" id="search_word">
                    <input type="text" class="form-control" value="<?= $search_word ?>" aria-label="...">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="value"><?= $filter2_arr[$id_type]; ?></span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <? foreach ($filter_arr as $key => $value) { ?>
                                <li data-id="<?= $key ?>"><a href="#"><?= $value ?></a></li>
                            <? } ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-1">
                <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
            </div>
            <div class="col-xs-7"></div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="statistic_filter">
                <div class="statistic_filter_title">Выберите вуз:</div>
                <div class="statistic_filter_list">
                <?= $form->field($model, 'id_university')->checkboxList($universities, ['class' => 'form_checkList'])
                    ->label(false); ?>
                </div>
                </div>
            </div>
        </div>
    </div>
    <?= $form->field($model, 'cat')->hiddenInput()->hint(false)->label(false); ?>
    <?= $form->field($model, 'id_type')->hiddenInput()->hint(false)->label(false); ?>
    <?= $form->field($model, 'search_word')->hiddenInput()->hint(false)->label(false); ?>
    <?php ActiveForm::end(); ?>
    <?php Pjax::end() ?>
</div>

backend/views/catalog-subcat/form.php
<?php

use yii\helpers\Url;
use common\models\CatalogSubcatCat;

/**
 *
 * @var $this yii\web\View
 * @var $model common\models\CatalogSubcat;
 * @var $modelCat common\models\CatalogSubcatCat;
 *
 */

$request = Yii::$app->request;
$edit = $request->get('edit');
$get = $request->get();
$id = isset($get['id']) ? intval($get['id']) : 0;
$cat = Yii::$app->request->get('cat');
$modelSubcatCat = null;
if (empty($cat) && ($id != 0)) {
    $modelSubcatCat = CatalogSubcatCat::findOne(['id_subcat' => $id]);
    if ($modelSubcatCat != null) {
        $cat = $modelSubcatCat->id_cat;
    }
}
if (is_null($modelSubcatCat)) {
    $modelSubcatCat = new CatalogSubcatCat();
}

$url_module = '/' . $request->getPathInfo();
$url_validate = str_replace('form', 'validate', $url_module);

if (!empty($cat)) {
    $url_show = Url::to(['catalog-subcat/show', 'cat' => $cat]);
} else {
    $url_show = Url::to(['catalog-cat/show']);
}

$url_return = 'Вернуться к списку';
if ($edit == null) {
    $model->loadDefaultValues();
    $modelCat->loadDefaultValues();
    if (!empty($cat)) {
        $modelCat->id_cat = $cat;
    }
    $url_action = str_replace('form', 'create', $url_module);
    $submit = "Добавить";
    $actions = 'Добавить новую методичку';
} else {
    $url_action = str_replace('form', 'update', $url_module);
    $submit = "Внести правки";
    $actions = "Изменить методичку";
}

$result = [
    'model' => $model,
    'modelSubcatCat' => $modelSubcatCat,
    'url_action' => $url_action,
    'url_validate' => $url_validate,
    'submit' => $submit,
    'id' => $id,
];
?>
    <header>
    <div id='section_header'>
        <div id='section_title'><?= $actions ?></div>
        <div id='section_url'><a href='<?= $url_show ?>' class='btn btn-primary section_button'><?= $url_return ?></a>
        </div>
    </div>
</header>
<?= $this->render('_form', ['result' => $result]) ?>