common/models/EmailTemplate.php
<?php
namespace common\models;

use Yii;
use yii\base\Exception;
use yii\db\ActiveRecord;
use common\components\Table;

/**
 * EmailTemplate model
 *
 * @property integer $id
 * @property string $title
 * @property string $subject
 * @property string $content
 * @property string $foto1
 * @property string $foto2
 * @property string $foto3
 * @property string $foto4
 * @property string $foto5
 * @property string $attachment1
 * @property string $attachment2
 * @property string $attachment3
 * @property string $attachment4
 * @property string $attachment5
 * @property integer $sort
 *
 */
class EmailTemplate extends ActiveRecord
{
    const STATUS_INACTIVE = 1;
    const STATUS_ACTIVE = 0;
    
    public function behaviors()
    {
        return [
        ];
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return Table::get('template');
    }
    
    public function formName()
    {
        return '';
    }
    
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название шаблона',
            'subject' => 'Тема письма',
            'content' => 'Содержание письма',
            'foto1' => 'Картинка №1',
            'foto2' => 'Картинка №2',
            'foto3' => 'Картинка №3',
            'foto4' => 'Картинка №4',
            'foto5' => 'Картинка №5',
            'attachment1' => 'Вложение №1',
            'attachment2' => 'Вложение №2',
            'attachment3' => 'Вложение №3',
            'attachment4' => 'Вложение №4',
            'attachment5' => 'Вложение №5',
            'sort' => 'Приоритет',
        ];
    }
    
    public function rules()
    {
        return [
            [
                [
                    'title',
                    'subject',
                    'content',
                ],
                'string',
            ],
            [
                [
                    'title',
                ],
                'required',
            ],
            [
                'sort',
                'integer',
            ],

        ];
    }

    public function getId()
    {
        return $this->id;
    }

    public function beforeValidate()
    {
        try {
            //
        } catch (Exception $e) {
            //
        }
        return true;
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            try {
            } catch (Exception $e) {
                //
            }
            return true;
        } else {
            return false;
        }
    }
}

backend/controllers/EmailTemplateController.php
<?php
namespace backend\controllers;

use Yii;
use yii\base\Exception;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;
use backend\components\IP;
use backend\components\Notice;
use common\models\Admin;
use common\models\EmailTemplate;
use backend\models\EmailTemplateUpload;
use backend\models\EmailTemplateSearch;

/**
 * EmailTemplate controller
 */
class EmailTemplateController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                //                'user' => 'common\models\Users',
                'rules' => [
                    [
                        'actions' => [
                            'login',
                            'error',
                        ],
                        // Define specific actions
                        'allow' => true,
                        // Has access
                        'roles' => ['@'],
                        // '@' All logged in users / or your access role e.g. 'admin', 'user'
                    ],
                    [
                        'allow' => false,
                        // Do not have access
                        'roles' => ['?'],
                        // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    
    public $params = [];
    /**
     * @inheritdoc
     */
    public $layout = '@app/views/layouts/main.php';
    
    public function actions()
    {
        return [
            'errorHandler' => [
                'errorAction' => 'site/login',
            ],
        ];
    }
    
    public function beforeAction($action)
    {
        return (Admin::checkAuth($this) && self::checkRights());
    }
    
    public function checkRights()
    {
        if (!Yii::$app->authManager->checkAccess(Yii::$app->view->params['id_role'], 'managementTemplate')) {
            $this->redirect('/site/norights/')->send();
            return false;
        }
        return true;
    }
    
    public function actionShow()
    {
        $searchModel = new EmailTemplateSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $data = [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ];
        return $this->render('show', $data);
    }
    
    /* @param integer $id
     * @return mixed
     */
    public function actionForm($id = 0)
    {
        $model = $id == 0 ? new EmailTemplate() : $this->findModel($id);
        return $this->render('form', [
            'model' => $model,
        ]);
    }
    
    public function actionCreate()
    {
        $model = new EmailTemplate();
        $post = Yii::$app->request->post();
        $errorFilesArray = [
            'foto' => [],
            'attachment' => [],
        ];
        
        if ($model->load($post) && $model->save()) {
            $id = $model->getPrimaryKey();
            $model->sort = $id;
            $model->update();
            
            $filePath = EmailTemplateUpload::filePath();
            if (isset($post['files'])) {
                foreach ($post['files'] as $key => $fileArray) {
                    $modelUploadFile = new EmailTemplateUpload();
                    $modelUploadFile->load($fileArray, '');

                    $nameFoto = 'foto' . $key;
                    $foto = UploadedFile::getInstance($modelUploadFile, '[' . $key . ']foto');
                    $modelUploadFile->foto = $foto;
                    
                    if (($foto && $foto->tempName) && ($modelUploadFile->validate())) {
                        $nameFile = implode('', [
                            md5(microtime(true)),
                            '.',
                            $foto->extension,
                        ]);
                        if ($foto->saveAs($filePath . $nameFile)) {
                            $model->$nameFoto = $nameFile;
                            EmailTemplateUpload::changeSize($model->$nameFoto, 'foto');
                        }
                    } elseif (!empty($modelUploadFile->errors['foto'])) {
                        $errorFilesArray['foto'] =
                            array_merge($errorFilesArray['foto'], $modelUploadFile->errors['foto']);
                    }

                    $nameAttachment = 'attachment' . $key;
                    $attachment = UploadedFile::getInstance($modelUploadFile, '[' . $key . ']attachment');
                    $modelUploadFile->attachment = $attachment;

                    if (($attachment && $attachment->tempName) && ($modelUploadFile->validate())) {
                        $nameFile = implode('', [
                            md5(microtime(true)),
                            '.',
                            $attachment->extension,
                        ]);
                        if ($attachment->saveAs($filePath . $nameFile)) {
                            $model->$nameAttachment = $nameFile;
                            EmailTemplateUpload::changeSize($model->$nameAttachment, 'attachment');
                        }
                    } elseif (!empty($modelUploadFile->errors['attachment'])) {
                        $errorFilesArray['attachment'] =
                            array_merge($errorFilesArray['attachment'], $modelUploadFile->errors['attachment']);
                    }
                }
            };
            $model->update();
            
            $url = array_merge([
                'form',
                'id' => $id,
                'edit' => 'ok',
            ], array_filter([
                'cat' => Yii::$app->request->get('cat'),
            ]));

            $errorText = '';
            foreach ($errorFilesArray as $key => $array) {
                if (!empty($array)) {
                    $errorText .= ' ' . implode(' ', $array);
                }
            }
            if (empty($errorText)) {
                Notice::send($message = 'Шаблон успешно создан', $id_type = Notice::info, $id = Url::to($url));
            } else {
                Notice::send($message = 'Шаблон создан с некоторыми ошибками.' . $errorText, $id_type = Notice::warning,
                    $id = Url::to($url));
            }
            
            echo "<script>document.location='" . Url::to($url) . "';</script>";
            return true;
        } else {
        }
        return false;
    }
    
    public function actionValidate()
    {
        $arrayError = [];
        
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost) {
            $model = new EmailTemplate();
            $post = Yii::$app->request->post();
            if ($model->load($post)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $arrayError = array_merge($arrayError, ActiveForm::validate($model));
                return $arrayError;
            } else {
            }
        }
        return false;
    }
    
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $post = Yii::$app->request->post();
        $errorFilesArray = [
            'foto' => [],
            'attachment' => [],
        ];
        
        if ($model->load($post) && $model->save()) {
            $id = $model->getPrimaryKey();

            $filePath = EmailTemplateUpload::filePath();
            if (isset($post['files'])) {
                foreach ($post['files'] as $key => $fileArray) {
                    $modelUploadFile = new EmailTemplateUpload();
                    $modelUploadFile->load($fileArray, '');

                    $nameFoto = 'foto' . $key;
                    $foto = UploadedFile::getInstance($modelUploadFile, '[' . $key . ']foto');
                    $modelUploadFile->foto = $foto;

                    if ($modelUploadFile->delete_foto) {
                        if (is_file($filePath . $model->foto)) {
                            unlink($filePath . $model->foto);
                        }
                        $model->$nameFoto = '';
                    }

                    if (($foto && $foto->tempName) && ($modelUploadFile->validate())) {
                        $nameFile = implode('', [
                            md5(microtime(true)),
                            '.',
                            $foto->extension,
                        ]);
                        if ($foto->saveAs($filePath . $nameFile)) {
                            $model->$nameFoto = $nameFile;
                            EmailTemplateUpload::changeSize($model->$nameFoto, 'foto');
                        }
                    } elseif (!empty($modelUploadFile->errors['foto'])) {
                        $errorFilesArray['foto'] =
                            array_merge($errorFilesArray['foto'], $modelUploadFile->errors['foto']);
                    }

                    $nameAttachment = 'attachment' . $key;
                    $attachment = UploadedFile::getInstance($modelUploadFile, '[' . $key . ']attachment');
                    $modelUploadFile->attachment = $attachment;

                    if ($modelUploadFile->delete_attachment) {
                        if (is_file($filePath . $model->attachment)) {
                            unlink($filePath . $model->attachment);
                        }
                        $model->$nameAttachment = '';
                    }

                    if (($attachment && $attachment->tempName) && ($modelUploadFile->validate())) {
                        $nameFile = implode('', [

backend/views/email-template/_form.php
<?php

/**
 *
 * @var $this yii\web\View
 * @var $result
 * @var $submit
 * @var $duplicate
 * @var $model common\models\EmailTemplate
 *
 */

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\validators\FileValidator;
use yii\widgets\ActiveForm;
use yii\web\View;
use backend\assets\Select2Asset;
use backend\assets\CkeditorAsset;
use backend\models\EmailTemplateUpload;
use backend\components\Common;
use backend\components\Notice;
use common\models\EmailTemplate;
use kartik\select2\Select2;

$bundle_ckeditor = CkeditorAsset::register(Yii::$app->view);
Select2Asset::register(Yii::$app->view);
$this->registerJsFile('/lib/ajexfilemanager/ajex.js', ['position' => View::POS_END]);

$fileUrl = EmailTemplateUpload::fileUrl();
$filePath = EmailTemplateUpload::filePath();

$db = Yii::$app->db;
extract($result, EXTR_OVERWRITE);
/**
 * @var $submit string
 * @var $id integer
 */

$form_arr = [
    'options' => ['class' => 'form-group'],
    'errorOptions' => ['class' => 'form_error'],
    'labelOptions' => ['class' => 'form_title'],
    'inputOptions' => ['class' => 'form_input'],
];
$radio_arr = [
    'errorOptions' => ['class' => 'form_error'],
    'labelOptions' => ['class' => 'form_title'],
    'inputOptions' => ['class' => 'form_radio'],
];

$modelUpload = new EmailTemplateUpload();
?>
    <div class="post-form">
        <?php $form = ActiveForm::begin([
            'id' => 'dynamic-form',
            'action' => [
                $url_action,
                'id' => $model->id,
            ],
            'fieldConfig' => $form_arr,
            //         'enableClientValidation' => true,
            'enableClientValidation' => false,
            'enableAjaxValidation' => true,
            'validationUrl' => $url_validate,
            'options' => [
                'enctype' => 'multipart/form-data',
            ],
        ]); ?>
        <article>
            <div class='section_stripe'></div>
            <div class='section_info'>
                <?php Notice::init(); ?>

                <?= $form->field($model, 'title')->textInput(); ?>
                <?= $form->field($model, 'subject')->textInput(); ?>
                <div class="section_title"><?= $model->getAttributeLabel('content') ?></div>
                <div class="section_input">
                <?= $form->field($model, 'content', [
                    'options' => [
                        'class' => 'form-group form-wysiwyg',
                    ],
                ])->textarea([])->label(false); ?>
                </div>
                <script>
                    $(function () {
                        var ckeditor = CKEDITOR.replace('content', {
                            customConfig: '/lib/ckeditor/config.js'
                        });
                        AjexFileManager.init({returnTo: 'ckeditor', editor: ckeditor});
                    });
                </script>

                <div class='section_title'>
                    <h3>Картинки</h3>
                    <span>в формате jpg, png или gif,
                    размер не более
                        <?= str_replace('и', '', Yii::$app->formatter->asShortSize((new FileValidator)->getSizeLimit())) ?>
                        </span>
                </div>
                <?php
                for ($i = 1; $i <= 5; $i++) {
                    $foto = 'foto' . $i;
                    ?>
                    <div class='section_title'><? echo $model->getAttributeLabel($foto); ?></div>
                    <?php
                    if (is_file($filePath . $model->$foto)) {
                        ?>
                        <div class="section_doc">
                        <div class="icon">
                            <? echo Html::a(Html::img($fileUrl . $model->$foto, ['width' => 100]), Url::to($fileUrl . $model->$foto), [
                                'data' => ['fancybox' => 'gallery'],
                                'target' => '_blank',
                            ]); ?>
                        </div>
                        <div class="title" title="<?= $model->$foto ?>">
                            <?
                            echo implode('', [
                                Common::formatLongName($model->$foto),
                                '<br><span>',
                                Common::formatFileSize(filesize($filePath . $model->$foto)),
                                '</span>',
                            ]);
                            ?>
                        </div>
                        <div class="delete">
                            <?php
                            echo $form->field($modelUpload, '[' . $i . ']delete_foto', [
                                'options' => ['class' => 'form-group form-checkbox',],
                            ])->checkbox(['class' => 'span-1']); ?>
                        </div>
                    </div>
                        <?php
                    }
                    ?>


                    <div class="section_checkbox">
                    <?php
                    echo $form->field($modelUpload, '[' . $i . ']foto', [
                        'options' => ['class' => 'form-group form-file',],
                    ])->fileInput(['accept' => '.jpg, .png, .gif'])->label(false); ?>
                    </div>
                    <?
                }
                ?>

                <div class='section_title'>
                    <h3>Вложения</h3>
                    <span>в формате pdf, jpg, png или gif,
                    размер не более
                        <?= str_replace('и', '', Yii::$app->formatter->asShortSize((new FileValidator)->getSizeLimit())) ?>
                        </span>
                </div>
                <?php
                for ($i = 1; $i <= 5; $i++) {
                    $attachment = 'attachment' . $i;
                    ?>
                    <div class='section_title'><? echo $model->getAttributeLabel($attachment); ?></div>
                    <?php
                    if (is_file($filePath . $model->$attachment)) {
                        ?>
                        <div class="section_doc">
                        <div class="icon">
                            <? echo Html::a('<i class="fa fa-file" aria-hidden="true"></i>',
                                Url::to($fileUrl . $model->$attachment), [
                                    'target' => '_blank'
                                ]); ?>
                        </div>
                        <div class="title" title="<?= $model->$attachment ?>">
                            <?
                            echo implode('', [
                                Common::formatLongName($model->$attachment),
                                '<br><span>',
                                Common::formatFileSize(filesize($filePath . $model->$attachment)),
                                '</span>',
                            ]);
                            ?>
                        </div>
                        <div class="delete">
                            <?php
                            echo $form->field($modelUpload, '[' . $i . ']delete_attachment', [
                                'options' => ['class' => 'form-group form-checkbox',],
                            ])->checkbox(['class' => 'span-1']); ?>
                        </div>
                    </div>
                        <?php
                    }
                    ?>


                    <div class="section_checkbox">
                    <?php
                    echo $form->field($modelUpload, '[' . $i . ']attachment', [
                        'options' => ['class' => 'form-group form-file',],
                    ])->fileInput(['accept' => '.jpg, .png, .gif'])->label(false); ?>
                    </div>
                    <?
                }
                ?>

            </div>

            <div class='section_stripe2'></div>
            <?php
            echo Html::submitButton($submit, [
                'id' => 'submiting',
                'class' => 'btn btn-primary section_submit',
            ]);
            ?>
        </article>
        <?php ActiveForm::end(); ?>
    </div>
<?
$this->registerJsFile('/js/template_add.js', ['position' => yii\web\View::POS_END]);

backend/views/email-template/_search.php
<?php
/**
 * @var $this yii\web\View
 * @var $model backend\models\TemplateSearch
 * @var $form yii\widgets\ActiveForm
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

$id_type = $model->getId_type();
$search_word = $model->getSearch_word();
$filter_arr = [
    1 => 'Частичное совпадение с любым из слов',
    2 => 'Частичное совпадение с каждым из слов',
    3 => 'Точное совпадение',
];
$filter2_arr = [
    1 => 'Любое из слов',
    2 => 'Все слова',
    3 => 'Как в запросе',
];
?>
<div class="post-search">
    <?php Pjax::begin(['id' => 'search']) ?>
    <?php $form = ActiveForm::begin([
        'action' => ['show'],
        'method' => 'get',
        'options' => ['data-pjax' => true, 'id' => 'search_form'],
    ]); ?>
    <div class="filter">
        <div class="row">
            <div class="col-xs-4">
                <div class="input-group" id="search_word">
                    <input type="text" class="form-control" value="<?= $search_word ?>" aria-label="...">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="value"><?= $filter2_arr[$id_type]; ?></span>
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <? foreach ($filter_arr as $key => $value) { ?>
                                <li data-id="<?= $key ?>"><a href="#"><?= $value ?></a></li>
                            <? } ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-1">
                <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
            </div>
            <div class="col-xs-7"></div>
        </div>
    </div>
    <?= $form->field($model, 'id_type')->hiddenInput()->hint(false)->label(false); ?>
    <?= $form->field($model, 'search_word')->hiddenInput()->hint(false)->label(false); ?>
    <?php ActiveForm::end(); ?>
    <?php Pjax::end() ?>
</div>

backend/views/email-template/form.php
<?php

use yii\helpers\Url;
use common\models\EmailTemplate;

/**
 *
 * @var $this yii\web\View
 * @var $model common\models\EmailTemplate;
 *
 */

$request = Yii::$app->request;
$edit = Yii::$app->request->get('edit');
$get = Yii::$app->request->get();
$id = isset($get['id']) ? intval($get['id']) : 0;

$url_validate = Url::to(['email-template/validate']);
$url_show = Url::to(['email-template/show']);

$url_return = 'Вернуться к списку';
if ($edit == null) {
    $model->loadDefaultValues();
    $url_action = Url::to(['email-template/create']);
    $submit = "Добавить";
    $actions = 'Добавить новый шаблон';
} else {
    $url_action = Url::to(['email-template/update']);
    $submit = "Внести правки";
    $actions = "Изменить шаблон";
}

$result = [
    'model' => $model,
    'url_action' => $url_action,
    'url_validate' => $url_validate,
    'submit' => $submit,
    'id' => $id,
];
?>
    <header>
    <div id='section_header'>
        <div id='section_title'><?= $actions ?></div>
        <div id='section_url'><a href='<?= $url_show ?>' class='btn btn-primary section_button'><?= $url_return ?></a>
        </div>
    </div>
</header>
<?= $this->render('_form', ['result' => $result]);

backend/views/email-template/show.php
<?php

/**
 * @var $this yii\web\View
 * @var $dataProvider yii\data\ActiveDataProvider
 * @var $searchModel backend\models\EmailTemplateSearch
 */

use yii\helpers\Html;
use yii\helpers\Url;
use kartik\grid\GridView;
use liyunfang\pager\LinkPager;
use common\models\EmailTemplate;
use backend\models\EmailTemplateUpload;
use backend\components\Notice;

$minSort = EmailTemplate::find()->min('sort');
$maxSort = EmailTemplate::find()->max('sort');
$rangeSort = [$minSort, $maxSort];

$fileUrl = EmailTemplateUpload::fileUrl();
$filePath = EmailTemplateUpload::filePath();

$url_catalog = Url::to(['email-template/show']);
$url_add = Url::to(array_filter([
    'email-template/form',
]));

$this->params['breadcrumbs'] = [];

?>
    <header>
        <div id='section_header'>
            <div id='section_title'>Шаблоны</div>
            <div id='section_url'></div>
        </div>
    </header>
    <article>
        <?= Html::a('<i class="fa fa-plus-circle" aria-hidden="true"></i>', $url_add, [
            'class' => 'add-user',
            'title' => 'Добавить шаблон',
        ]) ?>
        
        <?= $this->render('_search', ['model' => $searchModel]) ?>
        <?php Notice::init(); ?>
        <div class='kartiktable'>
            <?php
            echo GridView::widget([
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'filterSelector' => implode(',', [
                    "select[name='" . $dataProvider->getPagination()->pageSizeParam . "']",
                    "input[name='" . $dataProvider->getPagination()->pageParam . "']",
                ]),
                'pager' => [
                    'class' => LinkPager::className(),
                    'template' => '{pageButtons} {customPage} {pageSize}',
                    'pageSizeList' => [10, 20, 50, 100],
                    'customPageWidth' => 50,
                    'customPageBefore' => "&nbsp;Перейти на&nbsp;",
                    'customPageAfter' => "&nbsp;Показывать по&nbsp;",
                ],
                'pjax' => true,
                'pjaxSettings' => [
                    'options' => [
                        'id' => 'notes',
                    ],
                    'afterGrid' => implode("\r\n", [
                        "<div id='section_actions'>",
                        "<div id='section_delete_all'>",
                        "Удалить выделенные элементы?",
                        "</div>",
                        "</div>",
                    ]),
                ],
                'striped' => false,
                'hover' => true,
                'resizableColumns' => false,
                'rowOptions' => function($model, $key, $index, $grid) {
                    $class = $index % 2 ? '' : 'odd_tr';
                    return [
                        'key' => $key,
                        'index' => $index,
                        'class' => $class,
                        'id' => $model->id,
                    ];
                },
                'tableOptions' => [
                    'class' => 'kartik_table',
                    'id' => 'table_barrier_block',
                    'style' => 'width: 100%;',
                ],
                'floatHeader' => true,
                'floatHeaderOptions' => [
                    'position' => 'fixed',
                ],
                'layout' => "{items}\n{pager}\n{summary}",
                'panel' => [
                    'type' => 'primary',
                ],
                'toolbar' => [
                    '{toggleData}',
                ],
                'toggleDataOptions' => ['minCount' => 0],
                'columns' => [
                    [
                        'attribute' => 'id',
                        'filterInputOptions' => ['class' => 'form-control form-id'],
                        'contentOptions' => [
                            'class' => 'first_td right_td',
                            'width' => 30,
                        ],
                        'headerOptions' => ['width' => 30],
                    ],
                    [
                        'attribute' => 'title',
                    ],
                    [
                        'attribute' => 'sort',
                        'headerOptions' => [
                            'width' => 40,
                        ],
                        'contentOptions' => [
                            'width' => 40,
                        ],
                        'format' => 'raw',
                        'value' => function($model) {
                            return Html::tag('div', Html::input('text', 'sort', $model->sort), [
                                'class' => 'edit_div',
                            ]);
                        },
                    ],
                    [
                        'class' => 'kartik\grid\ActionColumn',
                        'header' => 'Действия',
                        'width' => '70px',
                        'headerOptions' => [
                            'class' => 'last_th',
                        ],
                        'contentOptions' => [
                            'class' => 'last_td middle_td',
                        ],
                        'template' => '{update} {delete}',
                        'buttons' => [
                            'update' => function($url, $model, $key) {
                                return Html::a('<i class="fa fa-pencil-square-o user-table--actions" aria-hidden="true"></i>', Url::to([
                                    'email-template/form',
                                    'id' => $model->id,
                                    'edit' => 'ok',
                                ]), [
                                    'class' => 'edit_td',
                                    'data-pjax' => 0,
                                    'title' => 'Редактирование шаблона',
                                ]);
                            },
                            'delete' => function($url, $model, $key) {
                                return Html::a('<i class="fa fa-trash user-table--actions" aria-hidden="true"></i>', Url::to([
                                    'email-template/remove',
                                    'id' => $model->id,
                                ]), [
                                    'class' => 'delete_td',
                                    'data-pjax' => 0,
                                    'title' => 'Удаление шаблона',
                                    'onclick' => "return confirm('Вы действительно хотите удалить шаблон?');",
                                ]);
                            },
                        ],
                    ],
                    [
                        'class' => 'kartik\grid\CheckboxColumn',
                        'width' => "40px",
                        'headerOptions' => [
                            'class' => 'delete-all',
                        ],
                        'contentOptions' => [
                            'class' => 'last_td delete',
                        ],
                    ],
                ],
            ]);
            ?>
        </div>

    </article>
<?php
$this->registerJsFile('/js/template_show.js?2', ['position' => yii\web\View::POS_END]);