backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Author;
use Yii;
use yii\web\Controller;
use common\models\Admin;

/**
 * Site controller
 */
class SiteController extends Controller
{
    #public $defaultRoute = 'site/login';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }
    
    /**
     * @inheritdoc
     */
    public $layout = '@app/views/layouts/login.php';
    
    public function actions()
    {
        return [
            'errorHandler' => [
                'errorAction' => 'site/login',
            ],
        ];
    }
    
    public function actionLogin()
    {
        return $this->render('login');
    }
    
    public function actionLogout()
    {
        $validate = Yii::$app->request->validateCsrfToken();
        if ($validate) {
            $data = Yii::$app->request->get();
            return $this->render('logout', ['data' => $data,]);
        }
        return true;
    }
    
    public function actionError()
    {
        return true;
        return $this->render('login');
    }
    
    public function actionNorights()
    {
        $this->layout = '@app/views/layouts/main.php';
        return $this->render('norights');
    }
    
    public function beforeAction($action)
    {
        if ($action->id == 'logout') {
        } elseif ($action->id == 'error') {
            $this->redirect(['site/login'], 302)->send();
        } else {
            $admin_login = Yii::$app->request->cookies->getValue('admin_login');
            $admin_hash = Yii::$app->request->cookies->getValue('admin_hash');
            if (!empty($admin_login) && !empty($admin_hash)) {
                $admin = Admin::findByAccessToken($admin_login, $admin_hash);
                if ($action->id == 'norights') {
                    Yii::$app->view->params['id_user'] = $admin->id;
                    Yii::$app->view->params['id_role'] = $admin->id_role;
                    return true;
                }
            }
            
            $author_login = Yii::$app->request->cookies->getValue('author_login');
            $author_hash = Yii::$app->request->cookies->getValue('author_hash');
            if (!empty($author_login) && !empty($author_hash)) {
                $author = Author::findByAccessToken($author_login, $author_hash);
                if ($action->id == 'norights') {
                    Yii::$app->view->params['id_user'] = $author->id;
                    Yii::$app->view->params['id_role'] = $author->id_role;
                    return true;
                }
            }
            
            if (!empty($admin)) {
                $this->redirect(['page/show'], 302)->send();
                return true;
            }
            if (!empty($author)) {
                $this->redirect(['solution-orders/management'], 302)->send();
                return true;
            }
        }
        return true;
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\bootstrap\ActiveForm;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\Cookie;
use frontend\components\Notice;
use backend\models\OrdersDocs;
use common\models\Clients;
use common\models\Downloads;
use common\models\Page;
use common\models\Settings;
use common\models\SettingsEmail;
use common\models\SolutionData;
use common\models\SolutionPosition;
use common\models\OrderCheck;
use common\models\SolutionOrderDesc;
use common\models\Orders;
use common\models\SolutionOrderData;
use common\models\OrderStatus;
use common\models\OrderType;
use common\components\Email;
use common\components\Order;
use frontend\models\OrderForm;
use frontend\models\OrderUpload;
use frontend\models\ReviewForm;
use frontend\models\ReverseForm;
use frontend\models\RecycleForm;
use frontend\models\SolutionForm;
use backend\components\Common;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = '@app/views/layouts/standard.php';
    public $defaultAction = 'index';
    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'errorHandler' => [
                'errorAction' => 'site/index',
            ],
        ];
    }
    
    /**
     * Displays homepage.
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionIndex()
    {
        $this->layout = '@app/views/layouts/main.php';
        $path = '/' . Yii::$app->request->getPathInfo();
        $meta = Page::find()->where(['nameurl' => $path])->one();
        if (null === $meta) {
            throw new NotFoundHttpException(Yii::t('yii', 'Page not found.'));
        }
        $settings = Settings::findOne(1);
        
        return $this->render('index', [
            'meta' => $meta,
            'settings' => $settings,
        ]);
    }
    
    public function actionAbout()
    {
        $this->layout = '@app/views/layouts/standard.php';
        $path = '/' . Yii::$app->request->pathInfo;
        $meta = Page::find()->where(['nameurl' => $path])->one();
        if (null === $meta) {
            $this->redirect('/')->send();
            exit;
        }
        $settings = Settings::findOne(1);
        
        return $this->render('index', [
            'meta' => $meta,
            'settings' => $settings,
        ]);
    }
    
    public function actionGb()
    {
        $this->layout = '@app/views/layouts/standard.php';
        $path = '/' . Yii::$app->request->pathInfo;
        $meta = Page::find()->where(['nameurl' => $path])->one();
        if (null === $meta) {
            $this->redirect('/')->send();
            exit;
        }
        $settings = Settings::findOne(1);
        
        return $this->render('gb', [
            'meta' => $meta,
            'settings' => $settings,
        ]);
    }
    
    public function actionOrder()
    {
        $this->layout = '@app/views/layouts/standard.php';
        $path = '/' . Yii::$app->request->pathInfo;
        $meta = Page::find()->where(['nameurl' => $path])->one();
        if (null === $meta) {
            $this->redirect('/')->send();
            exit;
        }
        $settings = Settings::findOne(1);
        
        return $this->render('order', [
            'meta' => $meta,
            'settings' => $settings,
        ]);
    }
    
    public function actionReviewValidate()
    {
        $arrayError = [];
        
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost) {
            $model = new ReviewForm();
            $post = Yii::$app->request->post();
            if ($model->load($post)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $arrayError = array_merge($arrayError, ActiveForm::validate($model));
                return $arrayError;
            } else {
            }
        }
        return false;
    }
    
    public function actionReviewCreate()
    {
        if (Yii::$app->request->isPost) {
            $model = new ReviewForm();
            $post = Yii::$app->request->post();
            if ($model->load($post) && $model->save()) {
                
                $id = $model->getPrimaryKey();
                $url = ['gb'];
                
                $params = [];
                $params['subject'] = "Новый отзыв на вашем сайте";
                $message = "
                <html>
                <body>
                <p>Здравствуйте! <br>";
                $message .= sprintf('На вашем сайте оставили отзыв в %s %s!<br><br>', Common::getDateTime($model->time_add, 'H:i:s'), Common::getDateTime($model->date_add, 'd.m.Y'));
                $message .= "---------------------------------------------------------------<br>";
                $message .= !empty($model->avtor) ? sprintf('Имя: %s<br>', HtmlPurifier::process($model->avtor)) : '';
                $message .= !empty($model->phone) ? sprintf('Телефон: %s<br>', HtmlPurifier::process($model->phone)) : '';
                $message .= !empty($model->title) ? sprintf('Тема: %s<br>', HtmlPurifier::process($model->title)) : '';
                $message .= sprintf("Сообщение:<br>%s<br><br><br><br>", Yii::$app->formatter->asNtext($model->message));
                $message .= sprintf("Спасибо что пользуетесь нашими услугами, с уважением %s</p>", Yii::getAlias('@frontendWebroot'));
                $message .= "
                </body> 
                </html>";
                
                $params['message'] = $message;
                $params['from'] = ["noreply@stud-city.ru" => "stud-city.ru"];

//                $settings = Settings::findOne(1);
//                $typeEmail = TypeEmail::Reverse;
//                if (!empty($settings->$typeEmail)) {
//                    $params['email'] = [$settings->$typeEmail];
//                    Email::send($params);
//                }
                
                $emailList = SettingsEmail::find()->all();
                
                if (!empty($emailList)) {
                    foreach ($emailList as $email) {
                        if (!empty($email->email)) {
                            $params['email'] = [$email->email];
                            Email::send($params);
                        }
                    }
                }
                
                $errorFilesArray = [];
                $errorText = '';
                foreach ($errorFilesArray as $key => $array) {
                    if (!empty($array)) {
                        $errorText .= ' ' . implode(' ', $array);
                    }
                }
                if (empty($errorText)) {
                    Notice::send($message = 'Ваш отзыв успешно отправлен!', $id_type = Notice::info, $id =
                        Url::to($url));
                } else {
                    Notice::send($message = 'Ваш отзыв отправлен с некоторыми ошибками.' . $errorText, $id_type =
                        Notice::warning, $id = Url::to($url));
                }
//                $this->redirect($url)->send();
//                return Yii::$app->response->redirect($url);
                
                echo "<script>document.location='" . Url::to($url) . "';</script>";
                exit;
            }
        }
        return false;
    }
    
    public function actionReverseValidate()
    {
        $arrayError = [];
        
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost) {
            $model = new ReverseForm();
            $post = Yii::$app->request->post();
            if ($model->load($post)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $arrayError = array_merge($arrayError, ActiveForm::validate($model));
                return $arrayError;
            } else {
            }
        }
        return false;
    }
    
    public function actionReverseCreate()
    {
        if (Yii::$app->request->isPost) {
            $model = new ReverseForm();
            $post = Yii::$app->request->post();
            if ($model->load($post) && $model->validate($post)) {
                
                $params = [];
                $filePath = OrderUpload::filePath();
                $dataArray = Json::decode($model->dataArray);
                if (!empty($dataArray)) {
                    foreach ($dataArray as $data) {
                        $nameFile = OrderUpload::upload($data);
                        if (!is_null($nameFile)) {
                            $params['attachments'][$filePath . $nameFile] = [
                                'fileName' => $nameFile,
                            ];
                        }
                    }
                }
                
                $url =
                    !empty(Yii::$app->request->referrer) ? str_replace(Yii::getAlias('@frontendWebroot'), '', Yii::$app->request->referrer) : ['index'];
                
                $params['subject'] = "Новое сообщение на вашем сайте";
                $message = "
                <html>
                <body>
                <p>Здравствуйте! <br>
                На вашем сайте написали сообщение!!<br><br>
                ---------------------------------------------------------------<br>";
                $message .= !empty($model->name) ? sprintf('Имя: %s<br>', HtmlPurifier::process($model->name)) : '';
                $message .= !empty($model->phone) ? sprintf('Телефон: %s<br>', HtmlPurifier::process($model->phone)) : '';
                $message .= !empty($model->email) ? sprintf('E-mail: %s<br>', HtmlPurifier::process($model->email)) : '';
                $message .= sprintf("Сообщение:<br>%s<br><br><br><br>", Yii::$app->formatter->asNtext($model->desc));
                $message .= sprintf("
                Спасибо что пользуетесь нашими услугами, с уважением %s</p> 

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->context->layout = 'general';

$this->title = $name;

?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <!--p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p-->

</div>

frontend/views/site/gb.php
<?php

/**
 * @var $this yii\web\View
 * @var $meta common\models\Page
 * @var $settings common\models\Settings
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use common\models\Review;
use common\models\ReviewReply;
use backend\components\Common;
use frontend\models\ReviewForm;
use frontend\components\Notice;

$this->title = $meta['metatitle'];
$this->params['metaDescription'] = $meta['description'];
$this->params['metaKeywords'] = $meta['keywords'];

$pathname = '/' . Yii::$app->request->getPathInfo();
$params = [
    'meta' => $meta,
];

$opinions =
    Review::find()->where(['subm' => 1])->orderBy(['date_add' => SORT_DESC, 'time_add' => SORT_DESC])->asArray()->all();

$results = ReviewReply::find()->orderBy(['date_add' => SORT_DESC, 'time_add' => SORT_DESC])->asArray()->all();
$replies = [];
foreach ($results as $result) {
    $comment = $result['comment'];
    if (!array_key_exists($comment, $replies)) {
        $replies[$comment] = [];
    }
    $replies[$comment][$result['id']] = $result;
}
$this->registerJsFile('/js/gb.js?20180218', ['position' => yii\web\View::POS_END]);

$reviewForm = new ReviewForm();

?>
<div id='content'>
<div id='catalog'>

    <?= $this->renderFile('@app/views/layouts/search.php', ['settings' => $settings]); ?>
    <div id='catalog_title' class="gb_title">
    <h1><span><?= $meta->title ?></span></h1>
    <div id='gb_click'><span>Написать отзыв</span></div>
    </div>
    <?php Notice::init(); ?>
    <div id='gb_form'>

    <?
    //    $fieldConfig = [
    //        'options' => ['class' => 'site-form-group gb_inputform'],
    //        'hintOptions' => [
    //            'tag' => 'p',
    //            'class' => 'site-hint-block',
    //        ],
    //        'errorOptions' => [
    //            'tag' => 'p',
    //            'class' => 'site-help-block site-help-block-error',
    //        ],
    //        'labelOptions' => [
    //            'class' => 'control-label gb_input_title'
    //        ],
    //        'inputOptions' => [
    //            'class' => 'site-form-control gb_input',
    //        ],
    //    ];
    $fieldConfig = [
        'options' => ['class' => 'site-form-group gb_inputform'],
        'hintOptions' => [
            'tag' => 'p',
            'class' => 'site-hint-block',
        ],
        'errorOptions' => [
            'tag' => 'p',
            'class' => 'site-help-block site-help-block-error',
        ],
        'labelOptions' => [
            'class' => 'control-label',
        ],
        'inputOptions' => [
            'class' => 'site-form-control',
        ],
    ];
    $form = ActiveForm::begin([
        'id' => 'review-form',
        'action' => [
            Url::to([
                'site/review-create',
                'id' => $reviewForm->id,
            ]),
        ],
        'fieldConfig' => $fieldConfig,
        'enableClientValidation' => false,
        'enableAjaxValidation' => true,
        'validationDelay' => 5000,
        'validationUrl' => Url::to(['site/review-validate']),
    ]);
    ?>
        <?= $form->field($reviewForm, 'avtor')->textInput([]); ?>
        <?= $form->field($reviewForm, 'phone')->textInput([]); ?>
        <?= $form->field($reviewForm, 'title')->textInput([]); ?>
        <?= $form->field($reviewForm, 'message', [
            'options' => ['class' => 'site-form-group gb_textareaform'],
        ])->textarea([]); ?>
        <div id='gb_send'><span>Отправить отзыв</span></div>
    <div id='gb_status'></div>
    </div>
    <?php ActiveForm::end(); ?>
    <div id='gb_comments'>
    <?php
    if (!empty($opinions)) {
        foreach ($opinions as $index => $opinion) {
            $comment = $opinion['id'];
            $avtor = Html::encode($opinion['avtor']);
            $message = nl2br(Html::encode($opinion['message'], false));
//            $date_add = Yii::$app->formatter->asDate($opinion['date_add'], 'php:d.m.Y');
            $date_add = Common::getDateTime($opinion['date_add'], 'd.m.Y');
            $reply = array_key_exists($comment, $replies) ? current($replies[$comment]) : [];
            $align = ($index % 2 == 1) ? " style='float: right; clear: none;'" : "";
            ?>
            <div class='gb_comment'<?= $align ?>>
            <div class='gb_comment_theme'><?= Html::encode($opinion['title']) ?></div>
            <div class='gb_comment_message'><?= $message ?></div>
            <div class='gb_comment_info'><?= $date_add . ', ' . $avtor ?></div>
                <?php
                if (!empty($reply)) {
                    ?>
                    <div class='gb_comment_stripe'></div>
                    <div class='gb_comment_reply'><span>Администрация:</span> <?= Html::encode($reply['message']) ?></div>
                    <?php
                }
                ?>
            </div>
            <?php
        }
    }
    ?>
</div>

</div>
</div>

frontend/views/site/index.php
<?php

/**
 * @var $this yii\web\View
 * @var $meta common\models\Page
 * @var $settings common\models\Settings
 */

$this->title = $meta['metatitle'];
$this->params['metaDescription'] = $meta['description'];
$this->params['metaKeywords'] = $meta['keywords'];

$pathname = '/' . Yii::$app->request->getPathInfo();
$params = [
    'meta' => $meta,
    'settings' => $settings,
];

if ($pathname == '/') {
    // 
} else {
    echo $this->render('page/id', $params);
}

frontend/views/site/order.php
<?php

/**
 * @var $this yii\web\View
 * @var $meta common\models\Page
 * @var $settings common\models\Settings
 */

use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use common\models\Review;
use common\models\ReviewReply;
use frontend\models\ReviewForm;
use frontend\components\Notice;

$this->title = $meta['metatitle'];
$this->params['metaDescription'] = $meta['description'];
$this->params['metaKeywords'] = $meta['keywords'];

$pathname = '/' . Yii::$app->request->getPathInfo();
$params = [
    'meta' => $meta,
];

$opinions =
    Review::find()->where(['subm' => 1])->orderBy(['date_add' => SORT_DESC, 'time_add' => SORT_DESC])->asArray()->all();

$results = ReviewReply::find()->orderBy(['date_add' => SORT_DESC, 'time_add' => SORT_DESC])->asArray()->all();
$replies = [];
foreach ($results as $result) {
    $comment = $result['comment'];
    if (!array_key_exists($comment, $replies)) {
        $replies[$comment] = [];
    }
    $replies[$comment][$result['id']] = $result;
}
$this->registerJsFile('/js/orders.js?20180218', ['position' => yii\web\View::POS_END]);

$reviewForm = new ReviewForm();

?>
<div id='content'>
<?= $this->renderFile('@app/views/layouts/search.php', ['settings' => $settings]); ?>
    <div id='order'>
    <?php Notice::init(); ?>
        <?= !empty($meta->content) ? sprintf('<div id="order_text">%s</div>', $meta->content) : ''; ?>
        <div id='order_descr'>
    <div id='order_descr_title'>- Предметы нашей специализации -</div>
    <div id='order_descr_info'>
    <div class='order_descr_info'><div>
    <div class='order_descr_title'><div>Технические предметы</div></div>
    <div class='order_descr_text'><div><?= $settings->order1 ?></div></div>
    </div></div>
    <div class='order_descr_info'><div>
    <div class='order_descr_title'><div>Гуманитарные предметы</div></div>
    <div class='order_descr_text'><div><?= $settings->order2 ?></div></div>
    </div></div>
    </div>
    </div>
    <div id='order_submit' class='md-trigger md-setperspective' data-modal='modal-2'>Оформить заказ</div>
</div>
</div>

frontend/views/site/search.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use backend\components\Common;
use Imagine\Image\Box;
use Imagine\Image\Point;
use Imagine\Image\BoxInterface;

$db = Yii::$app->db;
$request = Yii::$app->request;
$pathname = '/' . $request->getPathInfo();
$uri = $request->getUrl();
$word = $request->get('word');

$this->title = "Поиск";
if ($word != '') {
    $this->title .= "\"{$word}\"";
}
$this->params['metaDescription'] = '';
$this->params['metaKeywords'] = '';

$this->registerJsFile('/js/catalog.js', ['position' => yii\web\View::POS_END]);
$this->registerCssFile('/css/catalog.css', ['position' => yii\web\View::POS_BEGIN]);

$this->registerJsFile('/layout/bootstrap.min.js', ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/layout/dopoln/bootstrap-hover-dropdown.min.js', ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/lib/owl-carousel/owl.carousel.js', ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/layout/echo.min.js', ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/layout/bootstrap-slider.min.js', ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/layout/wow.min.js', ['position' => yii\web\View::POS_END]);
$this->registerJsFile('/layout/scripts.js', ['position' => yii\web\View::POS_END]);
#$this->registerCssFile('/css/main.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('/layout/bootstrap.min.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('/layout/main.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('/lib/owl-carousel/owl.carousel.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('/lib/owl-carousel/owl.transitions.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('/layout/animate.min.css', ['position' => yii\web\View::POS_BEGIN]);
#$this->registerCssFile('/layout/font-awesome.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('/layout/bootstrap-select.min.css', ['position' => yii\web\View::POS_BEGIN]);
$this->registerCssFile('https://fonts.googleapis.com/css?family=Exo+2:400,600&amp;subset=cyrillic', ['position' => yii\web\View::POS_BEGIN]);

$uploaddir = Yii::getAlias('@frontendDocroot/uploads/catalog/');
$urldir = Yii::getAlias('@frontendWebroot/uploads/catalog/');

$concat =
    $db->createCommand("SELECT id_cat, title, cat FROM catalog_cat_cat, catalog_cat WHERE catalog_cat_cat.id_cat = catalog_cat.id AND foto!='' AND archive='0'")
        ->queryAll();
foreach ($concat as $mcat) {
    $array[$mcat['cat']][$mcat['id_cat']] = $mcat['title'];
    $array2[$mcat['id_cat']][$mcat['cat']] = $mcat['title'];
}
?>
<div class="body-content outer-top-xs" id="top-banner-and-menu">
    <div class="container">
        <div class="row">
            <div class="col-xs-3 sidebar">
            <?php
            $params = [];
            echo $this->render('@frontend/views/site/aside_catalog', $params);
            ?>
            </div>
            <div class="col-xs-9 homebanner-holder">
                <div id='catalog'>
                    <div id='catalog_top'>
                        <div id='catalog_title'>
                            <div>
                            Каталог
                                <?php
                                if ($word != '') {
                                    echo "<span>/</span><span class='active'>{$word}</span>";
                                }
                                ?>
                            </div>
                        </div>
                        <?php
                        if ($word != '') {
                            ?>
                            <div id='catalog_nav'>
                                <div>
                                    <a href='/catalog/' title='Каталог'>Каталог</a>
                                    <span>/</span>
                                    <?= $word ?>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <?php
                    $conpos =
                        $db->createCommand("SELECT DISTINCT id FROM catalog_position, catalog_position_cat WHERE catalog_position_cat.id_position = catalog_position.id AND (article LIKE :word OR title LIKE :word) AND foto!='' AND archive='0'")
                            ->bindValues(['word' => '%' . $word . '%'])->queryAll();
                    $itemsperpage = 20;
                    $itemscount = !empty($conpos) ? count($conpos) : 0;
                    if ($itemscount != 0) {
                        $cpage = !is_null($request->get('page')) ? $request->get('page') : 1;
                        extract(Common::pagination($itemscount, $cpage, $itemsperpage), EXTR_OVERWRITE);
                        $conpos =
                            $db->createCommand("SELECT DISTINCT id, title, article, price, foto, (SELECT cat FROM catalog_position_cat WHERE catalog_position_cat.id_position = catalog_position.id ORDER BY sort DESC, id ASC LIMIT 1) AS cat FROM catalog_position, catalog_position_cat WHERE catalog_position_cat.id_position = catalog_position.id AND (article LIKE :word OR title LIKE :word) AND foto!='' AND archive='0' ORDER BY sort DESC, id ASC LIMIT $offset_page, $itemsperpage")
                                ->bindValues(['word' => '%' . $word . '%'])->queryAll();
                        if (empty($conpos) == false) {
                            ?>
                            <div id='catalog_pos'>
                            <?php
                            foreach ($conpos as $mcat) {
                                extract($mcat, EXTR_PREFIX_ALL, 'catalog');
                                $catalog_title = Html::encode($catalog_title);
                                $catalog_url = "/catalog/?id=" . $catalog_id;
                                $catalog_price_word = number_format($catalog_price, 0, '.', ',') . ' руб.';
                                $nav_cat = "";
                                $cur_cat = $catalog_cat;
                                while ($cur_cat != 0) {
                                    $url_cat = "/catalog/?cat=" . $cur_cat;
                                    $key = array_keys($array2[$cur_cat])[0];
                                    $name_cat = $array2[$cur_cat][$key];
                                    if ($cur_cat != $catalog_cat) {
                                        $nav_cat = "<span>/</span><a href='{$url_cat}'>{$name_cat}</a>" . $nav_cat;
                                    }
                                    $cur_cat = array_search($name_cat, $array2[$cur_cat]);
                                    if ($key == null) {
                                        $cur_cat = 0;
                                    }
                                }
                                $nav_cat = "<a href='/catalog/' title='Каталог'>Каталог</a>" . $nav_cat;
                                ?>
                                <div class='catalog_pos' data-id='<?= $catalog_id ?>'>
                                    <div>
                                        <span>
                                        <?php
                                        if (($catalog_foto != '') && (file_exists($uploaddir . $catalog_foto))) {
                                            ?>
                                            <div class='catalog_pos_foto'>
                                                <a title='<?= $catalog_title ?>' href='<?= $catalog_url ?>'>
                                                    <img src='<?= $urldir . $catalog_foto ?>'>
                                                </a>
                                            </div>
                                            <?php
                                        }
                                        ?>
                                            <div class='catalog_cat_desc'>
                                                 <div>
                                                    <a title='<?= $catalog_title ?>' href='<?= $catalog_url ?>' class='catalog_pos_title'>
                                                        <?= $catalog_title ?>
                                                    </a>
                                                    <div class='catalog_pos_nav'>
                                                        <?= $nav_cat ?>
                                                    </div>
                                                     <?php
                                                     if ($catalog_article != '') {
                                                         echo "<div class='catalog_pos_article'>{$catalog_article}</div>";
                                                     }
                                                     ?>
                                                </div>
                                            </div>
                                            <div class='catalog_pos_price'>
                                                <div class='catalog_pos_pricebox'>
                                                    <div>
                                                        <?= $catalog_price_word ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </span>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                        <?php
                            if ($pagescount > 1) {
                                ?>
                                <div id='catalog_pg'>
                                <?php
                                $arr = ['page', 'word'];
                                $query_array = [];
                                foreach ($arr as $value) if ($request->get($value) != null) {
                                    $query_array[$value] = $request->get($value);
                                }
                                echo Common::pagination_layout_show($query_array, $pagescount, $cpage, $stpage, $endpage, '');
                                ?>
                                </div>
                                <?php
                            }
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>